version: "3"

services:
  ridgepole:
    build: ./db
    volumes:
      - ./db:/db
    environment:
      - DATABASE_URL=${DATABASE_URL_RIDGEPOLE}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL_RIDGEPOLE}
  pg:
    image: postgres:11-alpine
    hostname: pg
    environment:
      - POSTGRES_DB="accounts"
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 5m
        max-file: "10"
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  pg-data:
    driver: local
