version: "3"

services:
  toshokan:
    image: programminglab/toshokan:latest
    depends_on:
      - mysql
    ports:
      - "53830:53830"
    volumes:
      - ./toshokan.toml:/go/toshokan.toml
    logging:
      options:
        max-size: 5m
        max-file: "10"

  mysql:
    image: mysql:5.7
    hostname: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "${TOSHOKAN_DB_PASSWORD}"
      MYSQL_DATABASE: "toshokan"
    volumes:
      - db-data:/var/lib/mysql
    logging:
      options:
        max-size: 5m
        max-file: "10"
    ports:
      - "33060:3306"

volumes:
  db-data:
    driver: local
