// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Authors", testAuthors)
	t.Run("BookAuthors", testBookAuthors)
	t.Run("Books", testBooks)
	t.Run("Lendings", testLendings)
}

func TestDelete(t *testing.T) {
	t.Run("Authors", testAuthorsDelete)
	t.Run("BookAuthors", testBookAuthorsDelete)
	t.Run("Books", testBooksDelete)
	t.Run("Lendings", testLendingsDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Authors", testAuthorsQueryDeleteAll)
	t.Run("BookAuthors", testBookAuthorsQueryDeleteAll)
	t.Run("Books", testBooksQueryDeleteAll)
	t.Run("Lendings", testLendingsQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Authors", testAuthorsSliceDeleteAll)
	t.Run("BookAuthors", testBookAuthorsSliceDeleteAll)
	t.Run("Books", testBooksSliceDeleteAll)
	t.Run("Lendings", testLendingsSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Authors", testAuthorsExists)
	t.Run("BookAuthors", testBookAuthorsExists)
	t.Run("Books", testBooksExists)
	t.Run("Lendings", testLendingsExists)
}

func TestFind(t *testing.T) {
	t.Run("Authors", testAuthorsFind)
	t.Run("BookAuthors", testBookAuthorsFind)
	t.Run("Books", testBooksFind)
	t.Run("Lendings", testLendingsFind)
}

func TestBind(t *testing.T) {
	t.Run("Authors", testAuthorsBind)
	t.Run("BookAuthors", testBookAuthorsBind)
	t.Run("Books", testBooksBind)
	t.Run("Lendings", testLendingsBind)
}

func TestOne(t *testing.T) {
	t.Run("Authors", testAuthorsOne)
	t.Run("BookAuthors", testBookAuthorsOne)
	t.Run("Books", testBooksOne)
	t.Run("Lendings", testLendingsOne)
}

func TestAll(t *testing.T) {
	t.Run("Authors", testAuthorsAll)
	t.Run("BookAuthors", testBookAuthorsAll)
	t.Run("Books", testBooksAll)
	t.Run("Lendings", testLendingsAll)
}

func TestCount(t *testing.T) {
	t.Run("Authors", testAuthorsCount)
	t.Run("BookAuthors", testBookAuthorsCount)
	t.Run("Books", testBooksCount)
	t.Run("Lendings", testLendingsCount)
}

func TestHooks(t *testing.T) {
	t.Run("Authors", testAuthorsHooks)
	t.Run("BookAuthors", testBookAuthorsHooks)
	t.Run("Books", testBooksHooks)
	t.Run("Lendings", testLendingsHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Authors", testAuthorsInsert)
	t.Run("Authors", testAuthorsInsertWhitelist)
	t.Run("BookAuthors", testBookAuthorsInsert)
	t.Run("BookAuthors", testBookAuthorsInsertWhitelist)
	t.Run("Books", testBooksInsert)
	t.Run("Books", testBooksInsertWhitelist)
	t.Run("Lendings", testLendingsInsert)
	t.Run("Lendings", testLendingsInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("BookAuthorToBookUsingBook", testBookAuthorToOneBookUsingBook)
	t.Run("BookAuthorToAuthorUsingAuthor", testBookAuthorToOneAuthorUsingAuthor)
	t.Run("LendingToBookUsingBook", testLendingToOneBookUsingBook)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("AuthorToBookAuthors", testAuthorToManyBookAuthors)
	t.Run("BookToBookAuthors", testBookToManyBookAuthors)
	t.Run("BookToLendings", testBookToManyLendings)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("BookAuthorToBookUsingBookAuthors", testBookAuthorToOneSetOpBookUsingBook)
	t.Run("BookAuthorToAuthorUsingBookAuthors", testBookAuthorToOneSetOpAuthorUsingAuthor)
	t.Run("LendingToBookUsingLendings", testLendingToOneSetOpBookUsingBook)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("AuthorToBookAuthors", testAuthorToManyAddOpBookAuthors)
	t.Run("BookToBookAuthors", testBookToManyAddOpBookAuthors)
	t.Run("BookToLendings", testBookToManyAddOpLendings)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Authors", testAuthorsReload)
	t.Run("BookAuthors", testBookAuthorsReload)
	t.Run("Books", testBooksReload)
	t.Run("Lendings", testLendingsReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Authors", testAuthorsReloadAll)
	t.Run("BookAuthors", testBookAuthorsReloadAll)
	t.Run("Books", testBooksReloadAll)
	t.Run("Lendings", testLendingsReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Authors", testAuthorsSelect)
	t.Run("BookAuthors", testBookAuthorsSelect)
	t.Run("Books", testBooksSelect)
	t.Run("Lendings", testLendingsSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Authors", testAuthorsUpdate)
	t.Run("BookAuthors", testBookAuthorsUpdate)
	t.Run("Books", testBooksUpdate)
	t.Run("Lendings", testLendingsUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Authors", testAuthorsSliceUpdateAll)
	t.Run("BookAuthors", testBookAuthorsSliceUpdateAll)
	t.Run("Books", testBooksSliceUpdateAll)
	t.Run("Lendings", testLendingsSliceUpdateAll)
}
