// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Authors", testAuthorsUpsert)

	t.Run("BookAuthors", testBookAuthorsUpsert)

	t.Run("Books", testBooksUpsert)
}
