// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
)

// PostSessionsHandlerFunc turns a function with the right signature into a post sessions handler
type PostSessionsHandlerFunc func(PostSessionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSessionsHandlerFunc) Handle(params PostSessionsParams) middleware.Responder {
	return fn(params)
}

// PostSessionsHandler interface for that can handle valid post sessions params
type PostSessionsHandler interface {
	Handle(PostSessionsParams) middleware.Responder
}

// NewPostSessions creates a new http.Handler for the post sessions operation
func NewPostSessions(ctx *middleware.Context, handler PostSessionsHandler) *PostSessions {
	return &PostSessions{Context: ctx, Handler: handler}
}

/*PostSessions swagger:route POST /sessions postSessions

ログイン

メールアドレスとパスワードでログインする。

*/
type PostSessions struct {
	Context *middleware.Context
	Handler PostSessionsHandler
}

func (o *PostSessions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostSessionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostSessionsCreatedBody post sessions created body
// swagger:model PostSessionsCreatedBody
type PostSessionsCreatedBody struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this post sessions created body
func (o *PostSessionsCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostSessionsCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostSessionsCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostSessionsCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
