// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi プロラボ図書館
プロラボの図書館理システムです。


    Schemes:
      https
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
