// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteSessionsNoContentCode is the HTTP code returned for type DeleteSessionsNoContent
const DeleteSessionsNoContentCode int = 204

/*DeleteSessionsNoContent No Content

swagger:response deleteSessionsNoContent
*/
type DeleteSessionsNoContent struct {
}

// NewDeleteSessionsNoContent creates DeleteSessionsNoContent with default headers values
func NewDeleteSessionsNoContent() *DeleteSessionsNoContent {

	return &DeleteSessionsNoContent{}
}

// WriteResponse to the client
func (o *DeleteSessionsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteSessionsUnauthorizedCode is the HTTP code returned for type DeleteSessionsUnauthorized
const DeleteSessionsUnauthorizedCode int = 401

/*DeleteSessionsUnauthorized Unauthorized

swagger:response deleteSessionsUnauthorized
*/
type DeleteSessionsUnauthorized struct {
}

// NewDeleteSessionsUnauthorized creates DeleteSessionsUnauthorized with default headers values
func NewDeleteSessionsUnauthorized() *DeleteSessionsUnauthorized {

	return &DeleteSessionsUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteSessionsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
