// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LoginCreatedCode is the HTTP code returned for type LoginCreated
const LoginCreatedCode int = 201

/*LoginCreated Created

swagger:response loginCreated
*/
type LoginCreated struct {

	/*
	  In: Body
	*/
	Payload *LoginCreatedBody `json:"body,omitempty"`
}

// NewLoginCreated creates LoginCreated with default headers values
func NewLoginCreated() *LoginCreated {

	return &LoginCreated{}
}

// WithPayload adds the payload to the login created response
func (o *LoginCreated) WithPayload(payload *LoginCreatedBody) *LoginCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the login created response
func (o *LoginCreated) SetPayload(payload *LoginCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LoginCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LoginUnauthorizedCode is the HTTP code returned for type LoginUnauthorized
const LoginUnauthorizedCode int = 401

/*LoginUnauthorized Unauthorized

swagger:response loginUnauthorized
*/
type LoginUnauthorized struct {
}

// NewLoginUnauthorized creates LoginUnauthorized with default headers values
func NewLoginUnauthorized() *LoginUnauthorized {

	return &LoginUnauthorized{}
}

// WriteResponse to the client
func (o *LoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
