// Code generated by go-swagger; DO NOT EDIT.

package sessions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// LogoutNoContentCode is the HTTP code returned for type LogoutNoContent
const LogoutNoContentCode int = 204

/*LogoutNoContent No Content

swagger:response logoutNoContent
*/
type LogoutNoContent struct {
}

// NewLogoutNoContent creates LogoutNoContent with default headers values
func NewLogoutNoContent() *LogoutNoContent {

	return &LogoutNoContent{}
}

// WriteResponse to the client
func (o *LogoutNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// LogoutUnauthorizedCode is the HTTP code returned for type LogoutUnauthorized
const LogoutUnauthorizedCode int = 401

/*LogoutUnauthorized Unauthorized

swagger:response logoutUnauthorized
*/
type LogoutUnauthorized struct {
}

// NewLogoutUnauthorized creates LogoutUnauthorized with default headers values
func NewLogoutUnauthorized() *LogoutUnauthorized {

	return &LogoutUnauthorized{}
}

// WriteResponse to the client
func (o *LogoutUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
